os:
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false

matrix:
  include:
  - name: fmt
    os: linux
    rust: stable
    before_script:
      - rustup component add rustfmt
    script:
      - cargo fmt --all -- --check
  - name: clippy
    os: linux
    rust: stable
    before_script:
      - rustup component add clippy
    script:
      - cargo clippy --all --lib --tests -- --deny warnings
  - name: coverage
    os: linux
    rust: stable
    sudo: required
    addons: # needed for `cargo install cargo-travis`
      apt:
        packages:
          - libcurl4-openssl-dev
          - libelf-dev
          - libdw-dev
          - binutils-dev
          - cmake
        sources:
          - kalakris-cmake
    script:
      - cargo install cargo-travis --debug || echo "cargo-travis has been already installed"
      - mkdir target # fix for cargo-coveralls
      - cargo coveralls --exclude-pattern "$PWD/target/,$PWD/libsodium-sys/src/sodium_bindings.rs"

script:
  - cargo test --all --verbose
  - cargo test --all --verbose --no-default-features --features std
  - cargo doc

branches:
    except:
    - /.*(.tmp)$/
