[package]
name = "libsodium-sys"
description = "FFI binding to libsodium"
repository = "https://github.com/dnaq/sodiumoxide.git"
keywords = ["libsodium", "NaCl", "crypto"]
version = "0.0.1"
authors = []
links = "sodium"
build = "build.rs"

[lib]
name = "libsodium-sys"
path = "lib.rs"

[dependencies]
libc = "*"
